<?php

$language = array
	(
	'title' => 'Hunger Games',
	
	'index' => 'Index',
	'fullwin' => 'FullScreen Mode',
	'backindex' => 'Back to Index',
	
	'register' => 'Register',
	'user' => 'User Data',
	'game' => 'Game',
	'map' => 'Map',
	'news' => 'News',
	'alive' => 'Survivors',
	'winner' => 'Winners',
	'rank' => 'Ranking',
	'help' => 'Help',
	'homepage' => 'Website',
	'admin' => 'Admin',
	'report' => 'Forum',
	
	'now' => 'Current Time',
	'gameversion' => 'Game Version',
	'gameinfo' => 'Game Info',
	'adminmsg' => 'Admin news',
	'systemmsg' => 'System Status',
	'username' => 'Username',
	'password' => 'Password',
	'welcome' => 'Welcome，{$cuser}！',
	'login' => 'Login',
	'numinfo' => 'ROUND $gamenum ',
	'gamedate' => '{$month}/{$day} {$week["$wday"]} {$hour}:{$min}',
	'back' => 'Back',
	'submit' => 'Submit',
	'reset' => 'Reset',
	
	'basicdata' => 'Account/Password',
	'advanceddata' => 'Personal Info',
	'creditsdata' => 'Credit Exchange',
	'opass' => 'Original Password',
	'npass' => 'New Password',
	'rnpass' => 'Repeat Password',
	'editpass' => 'Change Password',
	'username_comment' => 'maximum 12 bytes. No symbols allowed.',
	'password_comment' => 'maximum 24 bytes.',
	'motto' => 'Motto',
	'killmsg' => 'Kill Note',
	'lastword' => 'Last Note',
	'usertitle' => 'Title',
	'username_comment' => 'maximum 15 bytes, No symbols allowed.',
	'password_comment' => 'maximum 24 bytes, leave blank to ignore',
	'motto_comment' => 'Maximum 30 bytes.',
	'killmsg_comment' => 'Maximum 30 bytes.',
	'lastword_comment' => 'Maximum 30 bytes.',
	'credits' => 'Power Level',
	'credits2' => 'Gold',
	'lastgame' => 'last Game',
	'validgames' => 'Total Game',
	'wingames' => 'Win Game',
	'winrate' => 'Win Ratio',
	'end_achievement' => 'Ending Trophy',
	'mixitem_achievement' => 'Item Trophy',
	'battle_achievement' => 'Battle Trophy',
	'trap_achievement' => 'Trap Trophy',
	'other_achievement' => 'Challengers Trophy',
	
	
	'valid' => 'Entry Form',
	'validover' => 'Finished Entry Form',
	'enternotice' => 'ENTRY',
	'enterbattlefield' => 'GAME START!',
	'gamestart' => 'Game Start',
	'enter' => 'Enter',
	'quit' => 'Quit',
	'errormsg' => 'Error',
	
	'tutorial' => '游戏教程',
	'enterturorial' => '观看游戏教程',
	'nexttutorial' => '下一篇教程',
	
	'name' => 'Name',
	'gender' => 'Gender',
	'icon' => 'Avatar',
	'sNo' => 'ID',
	'level' => 'LV',
	'club' => 'Club',
	'hp' => 'HP',
	'sp' => 'SP',
	'att' => 'ATK',
	'def' => 'DEF',
	'combo' => 'LOCKDOWN',
	'duel' => 'DUEL',
	'exp' => 'EXP',
	'weather' => 'Weather',
	'status' => 'Status',
	'team' => 'Team',
	'inf' => 'Wounds',
	'pose' => 'Stance',
	'tactic' => 'Tactics',
	'kind1' => 'Kinds',
	'rage' => 'Rage',
	'killnum' => 'Kills',
	'money' => 'Coins',
	'equip' => 'Equipment',
	'pack' => 'Pack',
	'startpack' => 'Random Item',
	'skill' => 'MA',
	'command' => 'Commands',
	'wep' => 'Weapons',
	'arb' => 'Armor',
	'effect' => 'ATK',
	'cmd_choice' => 'What do you want to do?',
	'chat' => 'CHAT',
	'moneyunit' => ' Coins',
	'wp' => 'Blunt',
	'wk' => 'Slash',
	'wg' => 'Firearm',
	'wc' => 'Projectile',
	'wd' => 'Explosive',
	'wf' => 'Magic',
	'ss' => 'Song',
	'karma' => 'Karma',
	'skillpoint' => 'Skill Points',
	'newsnotice' => '<span class="evergreen">“May the Odds be ever in your favor!<br />You can review news here.<br />Good Luck.”</span>',
	'useitem' => '>>USE',
	'end' => 'GAME OVER！',
	'send' => 'SEND',
	'refresh' => 'REFRESH',
	'maptitle' => 'Map',
	);


?>
