<?php

$lang = array
(
	'gamename' => 'Engine Battle Royale',
	'succeed' => 'Succeed',
	'fail' => 'Failure',
	'exit' => 'Exit Installation Wizard',
	'enabled' => 'Enabled',
	'writeable' => 'Writeable',
	'unwriteable' => 'Unwriteable',
	'yes' => 'Yes',
	'no' => 'No',
	'unlimited' => 'Unlimited',

	'env_os' => 'OS Version',
	'env_php' => 'PHP Version',
	'env_mysql' => 'MySQL Version',
	'env_attach' => 'Attachment Path',
	'env_diskspace' => 'Disk Space',
	'env_dir_writeable' => 'Dir Writeable',

	'init_log' => 'Log init',
	'clear_dir' => 'Clear Dirs',
	'select_db' => 'Select Databases',
	'create_table' => 'Create Tables',
	'init_game' => 'Init Game Engine',
	'new_game' => 'Getting Ready for new game',

	'install_wizard' => 'BR Installation Wizard',
	'welcome' => 'Welcome to BR Installation Wizard',
	'current_process' => 'Current Step:',
	'show_license' => 'BR License Aggreement',
	'agreement' => 'Please read this license aggreement in its entirity',
	'agreement_yes' => 'I Agree',
	'agreement_no' => 'I do not Agree',
	'configure' => 'Write config.inc.php',
	'check_config' => 'Check Status of Config File',
	'check_existence' => 'Exists',
	'check_writeable' => 'Writeable',
	'edit_config' => 'Edit Config File',
	'variable' => 'Variable',
	'value' => 'Value',
	'comment' => 'Comment',
	'gamefounder' => 'Game Founder:',
	'gamefounder_comment' => 'This is the admin user',
	'dbhost' => 'Database Server:',
	'dbhost_comment' => 'Database Server Address, usually localhost',
	'dbuser' => 'Database Username:',
	'dbuser_comment' => 'Username used in Database',
	'dbpw' => 'Database Password:',
	'dbpw_comment' => 'Password used to login to the Database',
	'dbname' => 'Database Name:',
	'dbname_comment' => 'Database Name',
	'authkey' => 'Game Salt:',
	'authkey_comment' => 'A string used to encode information in-game',
	'tablepre' => 'Table prefix:',
	'tablepre_comment' => 'Used in multiple installations of BR Engine on 1 server',
	'tablepre_prompt' => 'If you are not installing more than 1 instance, please keep default',
	'moveut' => 'Server Time Differences:',
	'moveut_comment' => 'If by any chance there are time differences between the server and player machine input the difference here. Current Server Time:',
	'bbsurl' => 'BBS URL:',
	'bbsurl_comment' => 'If you are installing this as a BBS Plugin, input its URL here.',
	'gameurl' => 'Game URL:',
	'gameurl_comment' => 'The URL of your game installation',
	'save_config' => 'Save Config',

	'db_set' => 'Select Database',
	'db_use_existence' => 'Use Exist',
	'db_create_new' => 'Create New',

	'confirm_config' => 'All correct',
	'refresh_config' => 'Refresh',
	'recheck_config' => 'Recheck files',
	'check_env' => 'Check current Server Env',
	'compare_env' => 'Server Info',
	'env_required' => 'Recommended',
	'env_best' => 'Optimized',
	'env_current' => 'Current Server',
	'confirm_preparation' => 'Please Confirm Installation',
	'install_note' => 'Note',
	'add_admin' => 'Adding Admin Account',
	'start_install' => 'Starting Installation',
	'installing' => 'Checking Admin Account and installing game',
	'check_admin' => 'Checking Admin Account',
	'check_admin_validity' => 'Check Validity of Accounts',
	'admin_username_invalid' => 'Invalid Username!',
	'admin_password_invalid' => 'Invalid Password!',
	'admin_invalid' => 'Invalid Information!',
	'fail_reason' => 'Failure, Reason:',
	'go_back' => 'Go back',
	'init_file' => 'Init Files',
	'lock_exists' => 'You have already installed this game, for file safety, please delete install.php and all files under ./install. If you want to reinstall, please delete gamedata/install.lock Then run this wizard again.',

	'config_nonexistence' => 'Cannot find config.inc.php ! Please upload that file',
	'config_comment' => 'Please fill in your configs.',
	'config_unwriteable' => 'Config File unwriteable! Check chmod information, or upload the config file.',

	'php_version_430' => 'PHP Version too low!',
	'attach_enabled' => '允许/最大尺寸 ',
	'attach_enabled_info' => '您可以上传附件的最大尺寸: ',
	'attach_disabled' => '不允许上传附件',
	'attach_disabled_info' => '附件上传或相关操作被服务器禁止。',
	'mysql_version_323' => 'MySQL Version too low!',
	'unwriteable_template' => '(./templates) permission is not 777 or unwriteable，WYSIWYG Template Refresh function would be broken!',
	'unwriteable_gamedata' => '(./gamedata) permission is not 777 or unwriteable，Game Log and Backlog would be broken!',
	'tablepre_invalid' => 'Invalid table prefix, cannot contain dot character',
	'db_invalid' => 'Database Invalid, please recheck config',
	'db_auto_created' => 'Database do not exist, but has been created by wizard, installation would proceed normally',
	'db_not_null' => 'Instance of BR Engine already Installed! Are you sure you want to continue?',
	'db_drop_table_confirm' => 'If you want to continue, the last instance would be deleted!',

	'install_abort' => 'Installation Aborted due to faulty Config file.',
	'install_process' => 'Your server matches the requirements of the engine, please proceed with installation',
	'install_succeed' => 'Congrats! Installation Completed.',
	'goto_bbs' => '',
	'goto_game' => 'Click here to go to Game',


	'choice_or_new_db' => 'Please choose an existing database, or create a new one',
	'game_db_conf' => 'Database Config',
	'show_and_edit_db_conf' => 'Browse and Edit Database Configs',
	'choice_one_db' => 'Please select a Database',
	'db' => 'Databases',
	'check_user_and_pass' => 'Checking Database Account Permissions',
	'permission' => 'Permission',
	'status' => 'Status',
	
	'username' => 'Admin Username:',
	'username_comment' => 'First Game Admin Username',
	'brpswd' => 'Admin Password:',
	'brpswd_comment' => 'Notice this Admin is Level 9 Account in Database, while gamefounder overrides database and can log in without an game account.',
	'adminmsg' => 'Admin Message:',
	'adminmsg_comment' => 'Message shown on Front Page',
	'startmode' => 'Game Mode:',
	'startmode_comment' => 'Go to Admin Interface to set up game starttime',
	'starttime' => 'First Game Start At:',
	'iplimit' => 'IP Limit:',
	'iplimit_comment' => 'Set to 0 for Unlimited, otherwise this limits the amount of continues from 1 IP',

	'startmode_0' => 'Manual:',
	'startmode_1' => 'Set Time:',
	'startmode_2' => 'Every Hour:',
	'startmode_3' => 'Every Set Period:',
	'starttime_0' => 'Set Period:',
	'starttime_1' => 'Start Now:',
	'year' => '/',
	'month' => '/',
	'day' => '/',
	'hour' => ':',
	'min' => '',

	'license' => '<p class="subtitle">License Aggreement<br>Commerical Usage is Strictly Forbidden!</p>',

	'preparation' => '<li>Upload the contents of package onto your server</li><li>Edit Config.inc.php, you can get database information from your host.</li><li>If you are not using an WINNT System, chmod:<br>&nbsp; &nbsp; <b>./templates</b> 777;&nbsp; &nbsp; <b>./gamedata</b> 777;<br><b>&nbsp; &nbsp;<br></li>',

);

?>